### ISSUE TITLE
Separate ArcMap and ArcGIS Pro code

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-tool-addin-dotnet#642] opened 2020-01-14 14:54 UTC
To prepare for converting the addin to a Pro-only component going forward, we are making some structural changes to the solution:

1. Removing: ArcMapAddinCoordinateConversion project/dll
2. Removing: CoordinateConversion project/dll
3. Refactoring the Pro project to remove dependencies on former CoordinateConversion
    a. remove view inheritance
    b. remove no-longer-needed classes (super/abstract classes)
    c. remove mediator/dispatcher (ex: convert to RelayCommands) 
    d. use Pro styling for Dark Mode support
4. As part of this if you notice any hard-coded UI strings that should be converted to Resources (for I18n) please convert these to resources

**Comment by sumitzarkar** [comment] 2020-02-17 18:19
@dfoll @lfunkhouser @csmoore @OscarVilla1

We have implemented code for  following points:
 1. Removing: ArcMapAddinCoordinateConversion project/dll
 2. Removing:CoordinateConversionLibrary project/dll
 3. Refactoring the Pro project to remove dependencies on former CoordinateConversionLibrary
    a. remove view inheritance

Note: This build is work in progress and some build errors can be observed

**Comment by sumitzarkar** [comment] 2020-02-24 04:12
@dfoll @lfunkhouser @csmoore @OscarVilla1

We have completed refactoring, and have committed the code for it.

Note: We have observed that addin is crashing in one case and we are working on it.

**Comment by sumitzarkar** [comment] 2020-02-24 21:04
@lfunkhouser @csmoore @OscarVilla1@dfoll

Below are the repo steps to reproduce the crash we were experiencing:
1.	Launch the AddIn
2.	Activate “Map Point Tool”
3.	Click on “Add” button under “Output” section
4.	ArcGIS pro crashes with an error message

We have found the root cause for this and have fixed at our end, and we are testing it.

**Comment by sumitzarkar** [comment] 2020-02-25 04:24
@lfunkhouser @csmoore @OscarVilla1 @dfoll

We have pushed the code to fix the above mentioned crash.

**Comment by sumitzarkar** [comment] 2020-02-25 15:28
@lfunkhouser @csmoore @OscarVilla1 @dfoll

We have pushed the code Pro Style changes.

**Comment by csmoore** [comment] 2020-02-25 15:34
@sumitzarkar - would it be possible to change the buttons also - like you did for DistanceAndDirection - thanks

**Comment by sumitzarkar** [comment] 2020-02-26 21:36
@csmoore @dfoll @lfunkhouser

We have submitted the pull request for this ticket [Pull Request Link](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/644)

**Comment by lfunkhouser** [comment] 2020-03-02 17:14
@csmoore will merge PR into a "Pro 2.6 branch"

**Comment by sumitzarkar** [comment] 2020-03-05 00:13
@lfunkhouser @csmoore @dfoll 

We have implemented the following code review comment  and here is the [commit link](
https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/646/commits/eff8118d3ece199b7831cf2ff861ef7427fec30c):
1. Instead of NotificationObject, use the Pro sdk provided ViewModelBase
 2. Add the dependencies in Config.daml

**Comment by sumitzarkar** [comment] 2020-03-09 18:32
@lfunkhouser @csmoore @dfoll 

We implemented code to fix pro style issue for browse window [commit link](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/646/commits/f5212c8db9afb7f4238095eb5ebac118666035f8):


 - #647 Browse window does not stay consistent with Dark Theme mode while opening
 - #648 Browse window does not stay consistent with Dark Theme mode while importing

**Comment by csmoore** [comment] 2020-03-10 16:59
✔️  These issues have been tested and closed (Dark Mode Form issues) : #647 , #648

The remaining issues are : 

1. Combined duplicate Base Classes into one class/file:
TabBaseViewModel and ProTabBaseViewModel
OutputCoordinateViewModel and ProOutputCoordinateViewModel
2. Change a few base class objects from `ViewModelBase` to `PropertyChangedBase`  - comment here:  https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/646/commits/eff8118d3ece199b7831cf2ff861ef7427fec30c#r389223919

[(This comment also included on PR)](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/646#issuecomment-597197876)

**Comment by sumitzarkar** [comment] 2020-03-11 23:03
@lfunkhouser @csmoore @dfoll 

We implemented the code to combine duplicate Base Classes into one class/file [(commit link)](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/646/commits/7c8e0c457261eef1adbeddfbb3e0f97da64a6973):
1.  TabBaseViewModel and ProTabBaseViewMode
2.  OutputCoordinateViewModel and ProOutputCoordinateViewModel

**Comment by BrandonArmstrong** [comment] 2020-03-20 22:12
Verified following fixes while running through Coordinate Conversion add-in Checklist located here https://github.com/ArcGIS/solutions-defense-test-catalog/issues/279

* Crash mentioned in https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/642#issuecomment-590547611 does not occur
* Browse window(s) now stays consistent with Dark Theme Mode #647, #648

Verification was done using:
ArcGIS Pro v.2.6.0 alpha build 23705
Coordinate Conversion add-in version attached to issue
[CoordinateConversion.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/4361963/CoordinateConversion.zip)

**Closed as completed** 2020-03-23 16:27 UTC
Labels: A-feature, E-verified, CyberTech, V - Pro 2.6
